### ISSUE TITLE
Another Termin bot

### ISSUE THREAD

**Issue by ccomkhj** [conradkirschner/contact#1]
Hi @conradkirschner ! I found that you collected awesome stuff for Berliner!
Thanks for your work.

I recently developed visa termin bot, so love to be shared with other Berliners :)
Check here. https://github.com/ccomkhj/berlin-auslanderbehorde-termin-macro

It's more handy&intuitive version using docker compared to existing solutions.

**Comment by conradkirschner** [comment]
Hi @ccomkhj, 
I've added it to the list. Thanks for your work!
